### PR TITLE
Add missing image for OpenGraph

### PR DESCRIPTION
**Pull request by DanielRuf**
This PR adds the missing image so that the gpujs repo readme can display it again.

### CODE REVIEW

**Comment by HarshKhandeparkar** [comment]
Awesome! Thanks @DanielRuf.

**Comment by HarshKhandeparkar** [comment]
Sorry for the late merge.

**Comment by HarshKhandeparkar** [comment]
A new version of the site with your changes as well as new examples has been published! Check it out!

**Comment by DanielRuf** [comment]
It seems there is no website anymore at gpu.rocks.

**Comment by HarshKhandeparkar** [comment]
Oops. That's bad. Thanks for reporting.

**Comment by HarshKhandeparkar** [comment]
Forgot the CNAME. It should be fixed now. (It could take some time to
publish)

**Pull request merged**
