### PR TITLE
fix: Make build size MUCH smaller and remove jQuery altogether

### PR DESCRIPTION
**Pull request by robertleeplummerjr**
Some refactor work to make build smaller

### CODE REVIEW

**Comment by robertleeplummerjr** [comment]
Build size was much larger than 5mb prior, after we're at 1.06.  Also, no memory leak issues when building now.

**Comment by robertleeplummerjr** [comment]
This also guts the existing chart system, which uses plotly in favor of chartist (via react-chartist), but now with missing data.  Plotly, by itself, is 1mb.  That is insane.  Will be working this week to get new server data via benchmark (woot woot @HarshKhandeparkar!) and injecting it in here.

**Comment by robertleeplummerjr** [comment]
What to expect for charts with current stubbed data: 
Screen Shot 2019-09-14 at 6 06 05 PM

**Comment by HarshKhandeparkar** [comment]
Nice. We were using plotly as it had some extra features like zoom in etc. So now we will have to change our data JSON to work with chartist?

**Comment by robertleeplummerjr** [comment]
I think so.  The extra size I don't think justified using it.

**Comment by HarshKhandeparkar** [comment]
What is the format chartist uses? We'll have to change ours.

**Pull request merged**
