### PR TITLE
Replaced var with let

### PR DESCRIPTION
**Pull request by samu698**
Replaced var declaration in kernel because they are deprecated.

### CODE REVIEW

**Comment by HarshKhandeparkar** [comment]
Awesome! Thanks @samu698

**Comment by HarshKhandeparkar** [comment]
Sorry for the late merge.

**Comment by HarshKhandeparkar** [comment]
A new version of the site with your changes as well as new examples has been published! Check it out!

**Comment by samu698** [comment]
No problem, it was the smallest of the possible patches, i just wanted to get a merge :)

**Comment by HarshKhandeparkar** [comment]
Important is that you contributed to open source!

**Pull request merged**
